### ISSUE TITLE
no toast-container initialized

### ISSUE THREAD

**Issue by Behery** [Stabzs/vue-on-toast#3]
Hi @Stabzs 
Thanks for the work you're doing here. I'm trying to use this to display notifications but I'm getting the following error
`Error: No Toaster Containers have been initialized to receive toasts.`

I included https://unpkg.com/vue-on-toast@latest/dist/vue-on-toast.min.js and added 
<toast-container></toast-container> to my html
then celled 
`Vue.prototype.$vueOnToast.pop('error', 'title', 'error toast')` and I'm getting that error. What am I doing wrong here?

**Comment by Stabzs** [comment]
If you are calling the pop method without including the toaster-container component at least once in your application, this error will be thrown.  Please see https://github.com/Stabzs/vue-on-toast#add-toast-container.

If you can create a sample that reproduces the problem, I'd be more than happy to take a look at it.

**Comment by Behery** [comment]
I already included `<toast-container></toast-container>` in my html file. I'll try to make an example of this today and include it here.

**Comment by socendani** [comment]
oh! no!
incompatible with  bootstrap css:   https://unpkg.com/bootstrap/dist/css/bootstrap.min.css 
(in  cdn mode)
